### ISSUE TITLE
Update CI/CD

### ISSUE THREAD

**Issue by mikemimik** [mikemimik/dev-cli#2]
Currently the project came with travisci and circleci as the two tool used to manage CI. The goal is to switch this to GitHub Actions.

### Requirements
- [ ] #3 - should be using workflows in GitHub Actions
- [ ] #4 - should be running code coverage on the source files
- [ ] #3 - should be running tests on the source files
- [ ] #5 - should have a workflow for releasing a new version upon merge to the `master` branch
